### ISSUE TITLE
Query on Bumpversion and Punch.py.

### ISSUE THREAD

**Issue by kierun** [audreyr/cookiecutter-pypackage#206]
I came across [punch.py](https://github.com/lgiordani/punch/) which does a similar job to [bumpversion](https://github.com/peritus/bumpversion) but is actually maintained ([reference](https://github.com/lgiordani/punch/issues/6#issuecomment-223510585)). 

Would it be a good idea to use punch instead of bumpversion?

I have no agenda in saying this, just trying to be helpful. ☺

**Comment by eliasdorneles** [comment]
Hello @kierun, thanks for stopping by -- nice to know about punch.py !

Well, I prefer to make these decisions based on use-cases coming from users, because there is always a cost for switching (learning, doing the changes, testing, documenting, retraining users) that is often non-intuitive.

So, I'd consider switching if someone has a strong case for it -- like a serious bug in bumpversion or a killer feature in punch.py that they need (like, if users are having to change from bumpversion to punch.py).

It's okay that bumpversion doesn't have a high activity github repo, as long as it does what we expect -- sometimes a low activity github repo just mean the software is stable enough. :)

So, I'm going to close this now, and we can always reconsider in the future if necessary.
Thanks anyway!

**Comment by kierun** [comment]
Great answer! Thank you very much indeed.
