### ISSUE TITLE
Fix for autodoc on readthedocs.io

### ISSUE THREAD

**Issue by verginer** [audreyr/cookiecutter-pypackage#342]
* Date you used Cookiecutter PyPackage: 24/06/2017
* Cookiecutter version used, if any:
* Python version, if any: py36
* Operating System: OSX

### Description

I tried to get the autodoc to compile on rtfd but it failed until I removed the `rst` files
specified in the `docs/.gitignore`.
If they are not pushed and committed then read the docs cannot use autodoc

I propose to remove the files from that `docs/.gitignore` or find a way that it still compiles on readthedocs.io

**Comment by delgadom** [comment]
It does seem like one of three things are true:

1. the `docs/.gitignore` file should no be there
2. `sphinx-apidoc -o docs {{cookiecutter.package_slug}}` needs to be part of a pre- or post-commit hook in order to serve docs
3. Some ReadTheDocs configuration option allows apidoc to be run on their end, but this needs to be turned on, and the docs don't reflect that

Anyone else having this problem? I don't get api docs for any modules using this cookiecuter.

**Comment by monkeez** [comment]
I'm also having this issue, is there any solution? I'd prefer if ReadTheDocs could build these files so I wouldn't have to remember to do it every time my code changes.

**Comment by delgadom** [comment]
you can definitely get around the issue by removing `docs/.gitignore` or removing `*.rst` from that file. it's just annoying that packages cut with this template have this bug.

**Comment by pydanny** [comment]
Resolved
