### ISSUE TITLE
Template can create python modules with invalid names

### ISSUE THREAD

**Issue by v-for-vincent** [audreyr/cookiecutter-pypackage#6]
I set up a project recently, not knowing about the exact files that would be created. This led to a module with hyphens in its name being added to the project. It might be best to catch this error as soon as possible.

**Comment by glasslion** [comment]
This issue has been open for 2 years, is there any chance it would be fixed?
Many other  cookiecutter templates resolve this issue by introducing a new field, like package_name.

**Comment by audreyr** [comment]
@glasslion I'm not sure if I'll have time to get to this, but if you or anyone submits a pull request for it, I can make reviewing it a priority.

**Comment by eliasdorneles** [comment]
Perhaps a good-enough compromise would be warning in a pre_gen_project hook, something like?

```
import re

PACKAGE_REGEX = r'^[_a-zA-Z][_a-zA-Z0-9]+$'

repo_name = '{{ cookiecutter.repo_name }}'
if not re.match(PACKAGE_REGEX, repo_name):
    print('WARNING: %s is not a valid package name!' % repo_name)
```

**Comment by audreyr** [comment]
@eliasdorneles Sorry for the delay, been thinking about this. I think that's a good idea. If you want to resubmit the PR or just go ahead and commit that, go for it.

Additionally I think something that will help with this issue is 
1) Changing `repo_name` to be `project_slug` to be more explicit
2) Then creating the default value for it from `project_name` as follows:

```
  "project_slug": "{{ cookiecutter.project_name.lower().replace(' ', '_') }}",
```

I tried this in https://github.com/audreyr/cookiecutter-chrome-extension/blob/master/cookiecutter.json#L3 and it seemed pretty nice. So I'll go ahead and add this part to `cookiecutter.json` now.

**Comment by glasslion** [comment]
@audreyr I think @eliasdorneles 's suggestion is a little confusing. `-` is valid for python package names, it is widely used among the django, flask community.

**Comment by eliasdorneles** [comment]
@glasslion hm, I understand it's a valid package name, however it's an invalid module name (and cookiecutter-package uses the same name for both).
Maybe we could create yet another variable for the module name that would allow `python-boilerplate` as package name and use `python_boilerplate` as module name, though personally I like the convention of using the same name for package name and module name.

Do you have a suggestion?
