### ISSUE TITLE
Improve tutorial

### ISSUE THREAD

**Issue by audreyr** [audreyr/cookiecutter-pypackage#82]
Because this project is starting to get pretty complex, I started a tutorial on how to use cookiecutter-pypackage: http://cookiecutter-pypackage.readthedocs.org/en/latest/tutorial.html

Parts of it are still pretty bare. It could certainly use improvement.

**Comment by eliasdorneles** [comment]
Great idea!
Looks great, @audreyr, I'll work on expanding the bit about setting up Travis CI.

**Comment by NathanQ** [comment]
A 2013 mac had issues with setuptools and cryptography throwing errors on permissions and setuptools installation failing due to "error code 1 in /private/var/folders/f8/tkpb02px1knfv92w12gc3s0m0000gr/T/pip-build-mRXXm6/cryptography" --uh.

Reinstalled and upgraded setuptools globally as python user http://stackoverflow.com/a/33687813/2544138 then scrapped the virtualenv and upgraded pip and virtualenv http://stackoverflow.com/a/35867594/2544138 to versions 8.1.1 and 15.0.1. Made another virtualenv and requirements install worked.

**Comment by katialira** [comment]
I'm helping with this :)

**Comment by audreyr** [comment]
Merged, thanks @katialira!
